### ISSUE TITLE
No `MatButton` in the root

### ISSUE THREAD

**Issue by youncccat** [hamza1311/material-yew#11]
I have add material-yew as dependencies in my `Cargo.toml`:
```toml
[dependencies]
yew = "0.18.0"
wasm-bindgen = "0.2.67"
material-yew = "0.1.0"
yew-router = "0.15.0"
```
And then I'm use the `MatButton` from `material-yew` in my rust file
```rust
use material_yew::MatButton;
```
 but I get the following error
```
unresolved import `material_yew::MatButton`

no `MatButton` in the rootrustc(E0432)
```
Am I missing something?
